package index

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// TestExtractXLSXText exercises the real excelize-based extractor
// against an .xlsx fixture generated by openpyxl (a DIFFERENT
// library than the one under test — fixture creation and parsing
// must not share the same code path or the test is circular).
//
// Pins:
//   - Sheet 1's cell values land in the output, tab- + newline-
//     separated per row, double-newline between sheets.
//   - Hidden sheets are skipped — their content must NOT leak.
//   - Numeric cells render as their display value (excelize already
//     handles format-string resolution; we just verify the text
//     comes through).
func TestExtractXLSXText(t *testing.T) {
	body, err := os.ReadFile(filepath.Join("testdata", "sample.xlsx"))
	if err != nil {
		t.Fatalf("read fixture: %v", err)
	}
	got, err := extractXLSXText(body)
	if err != nil {
		t.Fatalf("extractXLSXText: %v", err)
	}

	// Sheet 1 content.
	for _, want := range []string{
		"Region", "Revenue", "Notes",
		"EMEA", "1500000", "Strong growth in Q3",
		"APAC", "Singapore office opened",
	} {
		if !strings.Contains(got, want) {
			t.Errorf("expected %q in extracted text, got:\n%s", want, got)
		}
	}

	// Sheet 2 content (multi-sheet extraction works).
	if !strings.Contains(got, "Confidential analyst memo") {
		t.Errorf("missing sheet 2 content; got:\n%s", got)
	}

	// Sheets are separated by a double newline so phrase queries
	// don't span sheet boundaries.
	if !strings.Contains(got, "\n\nConfidential analyst memo") {
		t.Errorf("expected double-newline before sheet 2; got:\n%s", got)
	}

	// Hidden sheets must NOT leak.
	if strings.Contains(got, "this-must-not-appear-in-extract") {
		t.Errorf("hidden sheet content leaked into extract; got:\n%s", got)
	}
}

// TestExtractXLSXText_Malformed surfaces non-zip input as an error
// (NOT ErrUnsupportedMimeType — the caller is committed at the
// switch in ExtractTextWithContext, so an extractor failure must
// re-deliver the job).
func TestExtractXLSXText_Malformed(t *testing.T) {
	_, err := extractXLSXText([]byte("this is not a zip archive"))
	if err == nil {
		t.Fatal("expected error on non-zip input, got nil")
	}
	if !strings.Contains(err.Error(), "index/xlsx") {
		t.Errorf("expected error message to be tagged with index/xlsx, got: %v", err)
	}
}

// TestExtractXLSXText_Empty exercises the empty-buffer edge — must
// surface a real error, not an empty-string success.
func TestExtractXLSXText_Empty(t *testing.T) {
	_, err := extractXLSXText(nil)
	if err == nil {
		t.Fatal("expected error on empty input, got nil")
	}
}
