package index

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/xuri/excelize/v2"
)

// TestExtractXLSXText exercises the real excelize-based extractor
// against an .xlsx fixture generated by openpyxl (a DIFFERENT
// library than the one under test — fixture creation and parsing
// must not share the same code path or the test is circular).
//
// Pins:
//   - Sheet 1's cell values land in the output, tab- + newline-
//     separated per row, double-newline between sheets.
//   - Hidden sheets are skipped — their content must NOT leak.
//   - Numeric cells render as their display value (excelize already
//     handles format-string resolution; we just verify the text
//     comes through).
func TestExtractXLSXText(t *testing.T) {
	body, err := os.ReadFile(filepath.Join("testdata", "sample.xlsx"))
	if err != nil {
		t.Fatalf("read fixture: %v", err)
	}
	got, err := extractXLSXText(body)
	if err != nil {
		t.Fatalf("extractXLSXText: %v", err)
	}

	// Sheet 1 content.
	for _, want := range []string{
		"Region", "Revenue", "Notes",
		"EMEA", "1500000", "Strong growth in Q3",
		"APAC", "Singapore office opened",
	} {
		if !strings.Contains(got, want) {
			t.Errorf("expected %q in extracted text, got:\n%s", want, got)
		}
	}

	// Sheet 2 content (multi-sheet extraction works).
	if !strings.Contains(got, "Confidential analyst memo") {
		t.Errorf("missing sheet 2 content; got:\n%s", got)
	}

	// Sheets are separated by a double newline so phrase queries
	// don't span sheet boundaries.
	if !strings.Contains(got, "\n\nConfidential analyst memo") {
		t.Errorf("expected double-newline before sheet 2; got:\n%s", got)
	}

	// Hidden sheets must NOT leak.
	if strings.Contains(got, "this-must-not-appear-in-extract") {
		t.Errorf("hidden sheet content leaked into extract; got:\n%s", got)
	}
}

// TestExtractXLSXText_Malformed surfaces non-zip input as an error
// (NOT ErrUnsupportedMimeType — the caller is committed at the
// switch in ExtractTextWithContext, so an extractor failure must
// re-deliver the job).
func TestExtractXLSXText_Malformed(t *testing.T) {
	_, err := extractXLSXText([]byte("this is not a zip archive"))
	if err == nil {
		t.Fatal("expected error on non-zip input, got nil")
	}
	if !strings.Contains(err.Error(), "index/xlsx") {
		t.Errorf("expected error message to be tagged with index/xlsx, got: %v", err)
	}
}

// TestExtractXLSXText_Empty exercises the empty-buffer edge — must
// surface a real error, not an empty-string success.
func TestExtractXLSXText_Empty(t *testing.T) {
	_, err := extractXLSXText(nil)
	if err == nil {
		t.Fatal("expected error on empty input, got nil")
	}
}

// TestExtractXLSXText_HiddenFirstSheetNoLeadingSeparator pins the
// regression: when the workbook's first sheet is hidden, the
// extractor must NOT emit a leading "\n\n" before the first
// visible sheet's body. The pre-fix implementation used the
// iteration index (sheetIdx > 0) to decide when to emit the
// separator, which incorrectly stuck a separator at the head of
// the output when sheet 0 was skipped. The fix tracks
// sb.Len() > 0 instead.
func TestExtractXLSXText_HiddenFirstSheetNoLeadingSeparator(t *testing.T) {
	body := buildXLSXWithHiddenFirstSheet(t)

	got, err := extractXLSXText(body)
	if err != nil {
		t.Fatalf("extractXLSXText: %v", err)
	}

	// Must NOT start with the sheet separator.
	if strings.HasPrefix(got, "\n\n") {
		t.Errorf("extracted text has leading sheet separator: %q", got)
	}

	// Visible sheet content must be present.
	if !strings.Contains(got, "visible-sheet-content") {
		t.Errorf("missing visible sheet content; got:\n%q", got)
	}

	// Hidden sheet content must NOT leak.
	if strings.Contains(got, "hidden-sheet-content") {
		t.Errorf("hidden sheet content leaked into extract; got:\n%q", got)
	}
}

// buildXLSXWithHiddenFirstSheet returns the bytes of a workbook
// whose first sheet is hidden and whose second sheet carries the
// only visible content. Using excelize on the producer side is
// acceptable here because the test is asserting on the
// hidden-sheet skip-and-separator behaviour, not on cell-value
// parsing — and re-using the same library lets us stand up the
// fixture in-process instead of carrying yet another binary
// blob in testdata/.
func buildXLSXWithHiddenFirstSheet(t *testing.T) []byte {
	t.Helper()

	f := excelize.NewFile()
	defer func() { _ = f.Close() }()

	// Excelize forbids hiding the only sheet and the active sheet
	// at the time of the SetSheetVisible call. So we (1) create
	// the visible sheet first, (2) activate it, (3) populate
	// values, and only THEN (4) hide the default "Sheet1".
	if err := f.SetCellValue("Sheet1", "A1", "hidden-sheet-content"); err != nil {
		t.Fatalf("set hidden cell: %v", err)
	}

	idx, err := f.NewSheet("Visible")
	if err != nil {
		t.Fatalf("create visible sheet: %v", err)
	}
	f.SetActiveSheet(idx)
	if err := f.SetCellValue("Visible", "A1", "visible-sheet-content"); err != nil {
		t.Fatalf("set visible cell: %v", err)
	}

	if err := f.SetSheetVisible("Sheet1", false); err != nil {
		t.Fatalf("hide sheet1: %v", err)
	}

	var buf bytes.Buffer
	if err := f.Write(&buf); err != nil {
		t.Fatalf("write workbook: %v", err)
	}
	return buf.Bytes()
}
