{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: zk-drive-secrets
  namespace: {{ include "zk-drive.namespace" . }}
  labels:
    {{- include "zk-drive.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $k, $v := .Values.secrets.data }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end }}
