# Secret Manager secrets consumed by the Cloud Run services.
#
# JWT_SECRET and CREDENTIAL_ENCRYPTION_KEY are generated by Terraform; the
# DB password is generated and reused as the Cloud SQL user password
# (cloudsql.tf). The full DATABASE_URL points at the Cloud SQL Proxy
# sidecar Cloud Run mounts at 127.0.0.1:5432.

resource "random_password" "db" {
  length  = 32
  special = false
}

resource "random_password" "jwt" {
  length  = 48
  special = false
}

resource "random_bytes" "credential_encryption_key" {
  length = 32
}

resource "google_secret_manager_secret" "jwt" {
  secret_id = "${local.name}-JWT_SECRET"

  labels = local.common_labels

  replication {
    auto {}
  }

  depends_on = [google_project_service.this]
}

resource "google_secret_manager_secret_version" "jwt" {
  secret      = google_secret_manager_secret.jwt.id
  secret_data = random_password.jwt.result
}

resource "google_secret_manager_secret" "credential_encryption_key" {
  secret_id = "${local.name}-CREDENTIAL_ENCRYPTION_KEY"

  labels = local.common_labels

  replication {
    auto {}
  }

  depends_on = [google_project_service.this]
}

resource "google_secret_manager_secret_version" "credential_encryption_key" {
  secret      = google_secret_manager_secret.credential_encryption_key.id
  secret_data = random_bytes.credential_encryption_key.base64
}

resource "google_secret_manager_secret" "db_password" {
  secret_id = "${local.name}-DB_PASSWORD"

  labels = local.common_labels

  replication {
    auto {}
  }

  depends_on = [google_project_service.this]
}

resource "google_secret_manager_secret_version" "db_password" {
  secret      = google_secret_manager_secret.db_password.id
  secret_data = random_password.db.result
}

# Full DATABASE_URL via the Cloud SQL Proxy sidecar (127.0.0.1:5432).
resource "google_secret_manager_secret" "database_url" {
  secret_id = "${local.name}-DATABASE_URL"

  labels = local.common_labels

  replication {
    auto {}
  }

  depends_on = [google_project_service.this]
}

resource "google_secret_manager_secret_version" "database_url" {
  secret      = google_secret_manager_secret.database_url.id
  secret_data = "postgres://${var.db_username}:${random_password.db.result}@127.0.0.1:5432/${var.db_name}?sslmode=disable"
}

resource "google_secret_manager_secret" "stripe_secret_key" {
  secret_id = "${local.name}-STRIPE_SECRET_KEY"

  labels = local.common_labels

  replication {
    auto {}
  }

  depends_on = [google_project_service.this]
}

resource "google_secret_manager_secret_version" "stripe_secret_key" {
  secret = google_secret_manager_secret.stripe_secret_key.id
  # Secret Manager rejects empty payloads; seed a single space when no key
  # is configured so the version (and the Cloud Run secret ref) is valid.
  secret_data = var.stripe_secret_key != "" ? var.stripe_secret_key : " "
}

resource "google_secret_manager_secret" "stripe_webhook_secret" {
  secret_id = "${local.name}-STRIPE_WEBHOOK_SECRET"

  labels = local.common_labels

  replication {
    auto {}
  }

  depends_on = [google_project_service.this]
}

resource "google_secret_manager_secret_version" "stripe_webhook_secret" {
  secret      = google_secret_manager_secret.stripe_webhook_secret.id
  secret_data = var.stripe_webhook_secret != "" ? var.stripe_webhook_secret : " "
}

# zk-object-fabric storage credentials. config.go's validateS3Group requires
# S3_ACCESS_KEY + S3_SECRET_KEY whenever S3_ENDPOINT (fabric_endpoint) is set.
# Seeded with a single space when unset (Secret Manager rejects empty
# payloads); a space still trips validateS3Group's TrimSpace check.
resource "google_secret_manager_secret" "s3_access_key" {
  secret_id = "${local.name}-S3_ACCESS_KEY"

  labels = local.common_labels

  replication {
    auto {}
  }

  depends_on = [google_project_service.this]
}

resource "google_secret_manager_secret_version" "s3_access_key" {
  secret      = google_secret_manager_secret.s3_access_key.id
  secret_data = var.fabric_access_key != "" ? var.fabric_access_key : " "
}

resource "google_secret_manager_secret" "s3_secret_key" {
  secret_id = "${local.name}-S3_SECRET_KEY"

  labels = local.common_labels

  replication {
    auto {}
  }

  depends_on = [google_project_service.this]
}

resource "google_secret_manager_secret_version" "s3_secret_key" {
  secret      = google_secret_manager_secret.s3_secret_key.id
  secret_data = var.fabric_secret_key != "" ? var.fabric_secret_key : " "
}

# Grant the application service account read access to each secret.
locals {
  app_secret_ids = {
    jwt                       = google_secret_manager_secret.jwt.secret_id
    credential_encryption_key = google_secret_manager_secret.credential_encryption_key.secret_id
    database_url              = google_secret_manager_secret.database_url.secret_id
    stripe_secret_key         = google_secret_manager_secret.stripe_secret_key.secret_id
    stripe_webhook_secret     = google_secret_manager_secret.stripe_webhook_secret.secret_id
    s3_access_key             = google_secret_manager_secret.s3_access_key.secret_id
    s3_secret_key             = google_secret_manager_secret.s3_secret_key.secret_id
  }
}

resource "google_secret_manager_secret_iam_member" "app" {
  for_each = local.app_secret_ids

  secret_id = each.value
  role      = "roles/secretmanager.secretAccessor"
  member    = "serviceAccount:${google_service_account.app.email}"
}
