//! Cross-language wire-format compatibility test.
//!
//! `testdata/envelope-vectors.json` is generated by running the Go
//! client_sdk against a fixed set of (DEK, plaintext, options)
//! tuples (see `/home/ubuntu/genvectors/main.go` for the producer
//! script and the doc comment in lib.rs). For every vector the
//! Rust crypto crate must:
//!
//!   1. produce byte-identical ciphertext when given the same DEK,
//!      plaintext, chunk size, AAD, and convergent-nonce mode —
//!      this is the strict guarantee that lets the desktop SDK
//!      replace Go writers and vice-versa, and
//!   2. successfully open the Go ciphertext back into the original
//!      plaintext.
//!
//! Random-nonce vectors are deliberately omitted because they
//! aren't reproducible across runs; that path is exercised by the
//! same-language roundtrip tests in `stream.rs`.

use serde::Deserialize;
use zk_sync_crypto::{decrypt_to_vec, encrypt_to_vec, DataEncryptionKey, Options};

#[derive(Deserialize)]
struct Fixture {
    vectors: Vec<Vector>,
}

#[derive(Deserialize)]
struct Vector {
    name: String,
    dek_hex: String,
    plaintext_hex: String,
    chunk_size: usize,
    chunk_aad_hex: String,
    convergent_nonce: bool,
    ciphertext_hex: String,
}

#[test]
fn matches_go_envelope_byte_for_byte() {
    let raw = include_str!("../testdata/envelope-vectors.json");
    let fixture: Fixture = serde_json::from_str(raw).expect("parse fixture");
    assert!(
        !fixture.vectors.is_empty(),
        "fixture is empty — regenerate it"
    );

    for v in &fixture.vectors {
        let dek_bytes = hex::decode(&v.dek_hex).expect("dek hex");
        let pt = hex::decode(&v.plaintext_hex).expect("plaintext hex");
        let aad = hex::decode(&v.chunk_aad_hex).expect("aad hex");
        let go_ct = hex::decode(&v.ciphertext_hex).expect("ciphertext hex");
        let dek = DataEncryptionKey::from_bytes(&dek_bytes).expect("dek length");

        let opts = Options {
            chunk_size: Some(v.chunk_size),
            convergent_nonce: v.convergent_nonce,
            chunk_aad: aad,
        };

        // Rust ⇒ Go: encrypt with Rust, compare bytes.
        let rust_ct = encrypt_to_vec(&pt, &dek, opts.clone())
            .unwrap_or_else(|e| panic!("encrypt {}: {e}", v.name));
        assert_eq!(
            rust_ct, go_ct,
            "vector {}: Rust ciphertext != Go ciphertext",
            v.name
        );

        // Go ⇒ Rust: decrypt the Go-produced ciphertext.
        let back = decrypt_to_vec(&go_ct, &dek, opts)
            .unwrap_or_else(|e| panic!("decrypt {}: {e}", v.name));
        assert_eq!(back, pt, "vector {}: decrypt result != plaintext", v.name);
    }
}
