//! Rust implementation of the ZK Drive Strict-ZK encryption envelope.
//!
//! This crate is the Rust mirror of `zk-object-fabric/encryption/client_sdk`
//! (Go). It seals plaintext with XChaCha20-Poly1305 in fixed-size chunks
//! using the exact frame format the Go SDK writes, so a file uploaded
//! from the Rust desktop SDK can be downloaded and decrypted by any
//! Go client (and vice versa).
//!
//! # Wire format
//!
//! For each chunk:
//!
//! ```text
//! | 24-byte XChaCha20-Poly1305 nonce | 4-byte BE ciphertext length | ciphertext (plaintext_len + 16-byte Poly1305 tag) |
//! ```
//!
//! All chunks except the last carry exactly [`DEFAULT_CHUNK_SIZE`] bytes
//! of plaintext. The last chunk may be shorter. The decryptor walks
//! frames sequentially; there is no separate framing manifest.
//!
//! # Additional Authenticated Data (AAD)
//!
//! Callers may bind per-chunk ciphertext to an object-level context
//! by populating [`Options::chunk_aad`]. When non-empty the AEAD AAD
//! for every chunk is:
//!
//! ```text
//! AAD = chunk_aad || "|" || big-endian uint64(chunk_index)
//! ```
//!
//! When `chunk_aad` is empty the SDK falls back to `AAD = nil` (i.e.
//! an empty byte string) for both seal and open — this preserves
//! ciphertext compatibility with pre-AAD objects sealed by older
//! versions of the Go SDK.
//!
//! # Convergent nonce mode
//!
//! [`Options::convergent_nonce`] switches the SDK from random
//! per-chunk nonces to deterministic content-derived nonces, derived
//! from the DEK via HKDF-SHA256 with the info prefix
//! `b"zkof-nonce-v1" || big-endian uint64(chunk_index)`. This is
//! required for the intra-tenant deduplication pattern documented in
//! the proposal; the trade-off is loss of forward secrecy for stored
//! ciphertext. Default is `false`.
//!
//! # Cross-language fixture
//!
//! `crates/crypto/testdata/envelope-vectors.json` carries reference
//! ciphertext bytes generated by the Go SDK. [`tests::go_compat`]
//! asserts byte-identical roundtrip — every change to either the Go
//! or the Rust envelope must keep this fixture green.

mod aad;
mod envelope;
mod error;
mod stream;

pub use envelope::{
    CustomerMasterKeyRef, DataEncryptionKey, EncryptionEnvelope, EncryptionMode,
    WrappedDataEncryptionKey,
};
pub use error::{Error, Result};
pub use stream::{
    decrypt_to_vec, encrypt_to_vec, ChunkAadFormat, Options, CONTENT_ALGORITHM,
    CONVERGENT_NONCE_INFO, DEFAULT_CHUNK_SIZE,
};

/// Canonical canonicalization of the per-object chunk AAD payload as
/// produced by [`ChunkAadFormat::Canonical`]. Exposed so callers
/// (e.g. the api-client crate) can produce the same bytes for
/// signing / display purposes without re-implementing the joiner.
pub fn canonical_chunk_aad(
    tenant_id: &str,
    bucket: &str,
    object_key_hash_hex: &str,
    version_id: &str,
) -> Vec<u8> {
    let mut out = Vec::with_capacity(
        tenant_id.len() + bucket.len() + object_key_hash_hex.len() + version_id.len() + 3,
    );
    out.extend_from_slice(tenant_id.as_bytes());
    out.push(b'|');
    out.extend_from_slice(bucket.as_bytes());
    out.push(b'|');
    out.extend_from_slice(object_key_hash_hex.as_bytes());
    out.push(b'|');
    out.extend_from_slice(version_id.as_bytes());
    out
}
