# AWS Secrets Manager secrets consumed by the ECS task definitions.
#
# Sensitive config (JWT signing key, credential-encryption key, the DB
# connection string with embedded password, and Stripe keys) is stored
# here and injected into containers via the task definition `secrets`
# block (see ecs.tf). Non-secret config is passed as plain `environment`
# entries.
#
# JWT_SECRET and CREDENTIAL_ENCRYPTION_KEY are generated by Terraform so a
# clean apply yields a working stack; rotate them out of band for real
# deployments. The DB password is also generated and reused as the RDS
# master password (rds.tf).

resource "random_password" "db" {
  length  = 32
  special = false
}

resource "random_password" "jwt" {
  length  = 48
  special = false
}

# CREDENTIAL_ENCRYPTION_KEY must decode to a 32-byte AES-256 key. The Go
# crypto.Codec accepts base64; generate 32 random bytes and base64 them.
resource "random_bytes" "credential_encryption_key" {
  length = 32
}

# JWT secret.
resource "aws_secretsmanager_secret" "jwt" {
  name        = "${local.name}/JWT_SECRET"
  description = "ZK Drive JWT signing secret"
}

resource "aws_secretsmanager_secret_version" "jwt" {
  secret_id     = aws_secretsmanager_secret.jwt.id
  secret_string = random_password.jwt.result
}

# Credential encryption key (AES-256-GCM, base64-encoded).
resource "aws_secretsmanager_secret" "credential_encryption_key" {
  name        = "${local.name}/CREDENTIAL_ENCRYPTION_KEY"
  description = "ZK Drive AES-256-GCM credential encryption key (base64)"
}

resource "aws_secretsmanager_secret_version" "credential_encryption_key" {
  secret_id     = aws_secretsmanager_secret.credential_encryption_key.id
  secret_string = random_bytes.credential_encryption_key.base64
}

# DB master password (also fed to RDS in rds.tf).
resource "aws_secretsmanager_secret" "db_password" {
  name        = "${local.name}/DB_PASSWORD"
  description = "RDS Postgres master password"
}

resource "aws_secretsmanager_secret_version" "db_password" {
  secret_id     = aws_secretsmanager_secret.db_password.id
  secret_string = random_password.db.result
}

# Full DATABASE_URL pointing at the PgBouncer sidecar (127.0.0.1:6432),
# which in turn pools connections to the RDS primary. Containers read
# DATABASE_URL directly; the sidecar owns the RDS credentials.
resource "aws_secretsmanager_secret" "database_url" {
  name        = "${local.name}/DATABASE_URL"
  description = "ZK Drive DATABASE_URL (via PgBouncer sidecar)"
}

resource "aws_secretsmanager_secret_version" "database_url" {
  secret_id     = aws_secretsmanager_secret.database_url.id
  secret_string = "postgres://${var.db_username}:${random_password.db.result}@127.0.0.1:6432/${var.db_name}?sslmode=disable"
}

# Direct DATABASE_URL straight to the RDS primary (no PgBouncer). Used by
# the short-lived cron tasks (reconciler / orphan-gc / audit-archiver),
# which would otherwise be held open by an essential sidecar.
resource "aws_secretsmanager_secret" "database_url_direct" {
  name        = "${local.name}/DATABASE_URL_DIRECT"
  description = "ZK Drive DATABASE_URL straight to the RDS primary (cron tasks)"
}

resource "aws_secretsmanager_secret_version" "database_url_direct" {
  secret_id     = aws_secretsmanager_secret.database_url_direct.id
  secret_string = "postgres://${var.db_username}:${random_password.db.result}@${aws_db_instance.primary.address}:5432/${var.db_name}?sslmode=require"
}

# Stripe keys. Always created so the task definition can reference a
# stable ARN; seeded empty when billing is not configured.
resource "aws_secretsmanager_secret" "stripe_secret_key" {
  name        = "${local.name}/STRIPE_SECRET_KEY"
  description = "Stripe secret key"
}

resource "aws_secretsmanager_secret_version" "stripe_secret_key" {
  secret_id = aws_secretsmanager_secret.stripe_secret_key.id
  # Secrets Manager rejects an empty SecretString (min length 1); seed a
  # single space when billing is not configured so a clean apply succeeds.
  secret_string = var.stripe_secret_key != "" ? var.stripe_secret_key : " "
}

resource "aws_secretsmanager_secret" "stripe_webhook_secret" {
  name        = "${local.name}/STRIPE_WEBHOOK_SECRET"
  description = "Stripe webhook signing secret"
}

resource "aws_secretsmanager_secret_version" "stripe_webhook_secret" {
  secret_id     = aws_secretsmanager_secret.stripe_webhook_secret.id
  secret_string = var.stripe_webhook_secret != "" ? var.stripe_webhook_secret : " "
}

locals {
  # Secrets injected into every application container, expressed in the
  # `secrets` shape ECS expects ({ name, valueFrom }). Names match the env
  # vars read by internal/config/config.go.
  app_secrets = [
    {
      name      = "DATABASE_URL"
      valueFrom = aws_secretsmanager_secret.database_url.arn
    },
    {
      name      = "JWT_SECRET"
      valueFrom = aws_secretsmanager_secret.jwt.arn
    },
    {
      name      = "CREDENTIAL_ENCRYPTION_KEY"
      valueFrom = aws_secretsmanager_secret.credential_encryption_key.arn
    },
    {
      name      = "STRIPE_SECRET_KEY"
      valueFrom = aws_secretsmanager_secret.stripe_secret_key.arn
    },
    {
      name      = "STRIPE_WEBHOOK_SECRET"
      valueFrom = aws_secretsmanager_secret.stripe_webhook_secret.arn
    },
  ]

  # Same set as app_secrets but pointing at the direct DATABASE_URL, for
  # the short-lived cron tasks that don't run a PgBouncer sidecar.
  cron_secrets = [
    {
      name      = "DATABASE_URL"
      valueFrom = aws_secretsmanager_secret.database_url_direct.arn
    },
    {
      name      = "JWT_SECRET"
      valueFrom = aws_secretsmanager_secret.jwt.arn
    },
    {
      name      = "CREDENTIAL_ENCRYPTION_KEY"
      valueFrom = aws_secretsmanager_secret.credential_encryption_key.arn
    },
    {
      name      = "STRIPE_SECRET_KEY"
      valueFrom = aws_secretsmanager_secret.stripe_secret_key.arn
    },
    {
      name      = "STRIPE_WEBHOOK_SECRET"
      valueFrom = aws_secretsmanager_secret.stripe_webhook_secret.arn
    },
  ]

  # ARNs the task execution role must be allowed to read.
  app_secret_arns = [
    aws_secretsmanager_secret.database_url.arn,
    aws_secretsmanager_secret.database_url_direct.arn,
    aws_secretsmanager_secret.jwt.arn,
    aws_secretsmanager_secret.credential_encryption_key.arn,
    aws_secretsmanager_secret.stripe_secret_key.arn,
    aws_secretsmanager_secret.stripe_webhook_secret.arn,
    aws_secretsmanager_secret.db_password.arn,
  ]
}
